### ISSUE TITLE
add parameter to configure line breaks during formatting

### ISSUE THREAD

**Issue by niels1voo** [Ekryd/sortpom#40] opened 2016-06-22 15:08 UTC
Intellij default xml formatter puts line breaks in long lines.  The value add for this project is the sorting, not the formatting.  I would like to see the following parameter added to the configuration.
`<breakLongLines>` default false and/or `<format>` default it to false.

**Comment by Ekryd** [comment] 2016-06-22 21:28
Part duplicate of #38 
The SortPom plugin is built on top of the JDom 1.1.3 library and that library does not have a line width option to format the xml. 
So unfortunately I cannot support line width in the plugin.

Also, when re-sorting elements the whole xml structure is processed by the xml parser and the output will always be created by the xml parser. That means that the plugin cannot reorder elements without formatting the output.

I have thought about changing the xml framework, but that will unfortunately take too much time to do.

**Closed** 2016-07-11 18:33 UTC
