### ISSUE TITLE
Add newlines on sort format

### ISSUE THREAD

**Issue by SvenssonWeb** [Ekryd/sortpom#61] opened 2018-03-29 14:12 UTC
Hi,

When specifying `<keepBlankLines>false</keepBlankLines>` no empty lines are preserved.

I haven't found any configuration for this, and it does not respect the newlines in the format file.

Is it possible to enforce newlines between sections as part of the sort/formatting?

**Comment by Ekryd** [comment] 2018-03-29 15:14
Hi,

This is partly a duplicate of #57.
The format file ignores all whitespace as only the xml content is parsed. 

The easiest way to solve your problem is to add newlines where you want them and then use the `<keepBlankLines>true</keepBlankLines>`. The plugin will then preserve those newlines.

Otherwise, do you have a suggestion how to indicate blank lines for sections? And which sections would you like to enforce newlines for?

**Comment by SvenssonWeb** [comment] 2018-04-01 14:14
The way I think about it would be some sort of <newLine/> construct in the "sort config file".
Given `<keepBlankLines>true</keepBlankLines>` this would add newlines where there are none, otherwise do nothing, and `<keepBlankLines>false</keepBlankLines>` would result in only the newlines specified in the "sort config file".

As an example, say I'd like to enforce this separation in the pom files:
```
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.group.id</groupId>
    <artifactId>my-project-id</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <name>Name of Project</name>
    <url>http://www.company.com/department/project</url>
```
The config file would look like this:
```
    <modelVersion/>
    <newLine/>
    <groupId/>
    <artifactId/>
    <version/>
    <newLine/>
    <name/>
    <url/>
```

**Comment by Ekryd** [comment] 2018-04-04 05:32
I would not change the behaviour of an existing parameter since that would create too much confusion for existing users but the `<newLine/>` could be worth investigating.

I guess that the newLine would always follow the previous element, so enforcing newline after modelVersion and version. How about repeating elements, what would be the outcome of

```
		<dependencies>
			<dependency>
				<groupId />
				<artifactId />
				<version />
				<classifier />
			</dependency>
                        </newLine>
		</dependencies>
```

Would that add a newLine after every dependency?

**Comment by SvenssonWeb** [comment] 2018-04-05 14:29
For simplicity I would argue that this would add a newline after each dependency.

You could add additional logic to be able to add lines based on predicates (e.g `<scope/>` changed).
But this would add a ton of complexity, where the use case I see is to be able to separate singleton constructs (e.g `<build/>`, `<dependencyManagement/>` etc.)

**Comment by Ekryd** [comment] 2018-04-12 16:42
Started with a small test to see the actual custom sort order file. We will see if these newlines can be picked up. One thing though, the <newLine> till be marked with red since it isn't part of the http://maven.apache.org/maven-v4_0_0.xsd

**Comment by Ekryd** [comment] 2018-05-05 17:08
I am sorry to say that I won't fix this issue. 

I started to have a look WrapperFactoryImpl.addElementsToSortOrderMap and it is possible to make some functionality to indicate newlines from the next element. It is also possible to change the ElementSortOrderMap to store this newline information and finally use this information during the sorting of the elements. 

The problem is that I simply do not have the time to do these changes. You are very welcome to make pull requests if you would like to contribute.

**Closed** 2018-05-05 17:11 UTC

**Comment by SvenssonWeb** [comment] 2018-05-14 13:35
Thank you for looking into it. I'll definitely look into it when I get the time.
