### ISSUE TITLE
LATEST using in pom is deprecated and will be removed from maven 4

### ISSUE THREAD

**Issue by hazendaz** [Ekryd/sortpom#345] opened 2023-07-28 16:36 UTC
I see you changed your latest ITs to use LATEST all over, that is deprecated for long time.  It will see you end up with future problems.  If you were trying to reduce possibly what bots suggest on updates, add properties to your root pom to control those and keep just the one per the what appears many usage of same so bot at worst will only raise the single pull requests.

**Comment by Ekryd** [comment] 2023-07-28 18:34
Hi! Thanks for the concern. The problem is that the bots updated the pom file, but not the expected pom file in the integration tests, causing a lot of manual correcting overhead for me. 
I also experimented with creating separate directories for expected pom and such, but no success. 
I’m aware that LATEST is deprecated, but this solution works best for me right now. 😃

**Comment by Ekryd** [comment] 2023-07-28 18:37
A public release of Maven 4 might change everything though 🤞

**Comment by hazendaz** [comment] 2023-07-28 19:33
Understood, no problem then for now.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Ekryd** [comment] 2023-07-28 20:32
Have you tried out Maven 4 with SortPom yourself? Are there are any known problems

**Comment by hazendaz** [comment] 2023-07-28 22:20
Haven't tried with sortpom.  Have with others.  Maven 4 definitely is not ready for prime time.  I have it running in parallel on some repos in GHA and there are oddities like enforcer plugin with jdk 17 doesn't seem to work correctly which ends up blocking my other plugins usage. My guess we won't see GA until 2024.

Given all the micro issues popping on 3.9.x, they have a ways to go.

You may want to look into renovate for lib updates.  It just works better.

I'm eventually going to make sure to run 4 alphas against all plugins I support.  I know code wise we all have a lot to fix up and there isn't much documentation on how to fix some issues.  Even maven hasn't complied with all their changes either.

I did sign up to their dev mailing list a while ago which does help understand where they are trying to go.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Ekryd** [comment] 2023-07-29 10:53
Renovate sounds interesting. I will have to look into that, especially since I have a local GitLab instance that cannot run dependabot. And if it is a bit more configurable, then it can solve my IT tests as well. 
Interesting that you have repos with Maven 4 running in parallel, do you have a link where I can see it setup?
Great tips!

**Comment by hazendaz** [comment] 2023-08-19 23:51
Here is an example of where I have maven 4 running on github actions -> https://github.com/spotbugs/spotbugs-maven-plugin/blob/spotbugs/.github/workflows/it-maven-4.0.0.yaml

**Comment by Ekryd** [comment] 2023-08-21 12:21
Thanks for all the information!
Tried out Renovate and it work much better than Dependabot. I was able to get rid of all LATESTS as Renovate handles my integration tests out of the box.
I will also try to setup a job for Maven 4, but I will do that in a separate Jira.
Closing this issue now and if you see anything else that can be improved, your input is always welcome

**Closed by Ekryd** 2023-08-21 12:21 UTC
